#!/system/bin/sh
# This is an init.d script to control some aspects of the kernel
# Please make sure that you know what you are doing!
# Uncomment all parts of the script you want to use by deleting the beginning "#" in the code-line.
# "echo 1" means enabled, "echo 0" means disabled, "echo xx" means that you have to replace the "xx" with a value of your choice.
# If something goes wrong, delete this file and reboot. It can also be deleted from TWRP file manager.
# Script written by darkened_sky


#------BOEFFLA SOUND 1.6.7 (by Lord Boeffla)------#

#Enable Boeffla sound
echo 1 > /sys/class/misc/boeffla_sound/boeffla_sound

#Microphone volume in-call
#This setting allows you to control the microphones sensitivity for phone calls (only)
#-->min: 0, max: 31, step: 1, default: 25
echo 23 > /sys/class/misc/boeffla_sound/mic_level_call

#Microphone volume general
#This setting allows you to control the microphones sensitivity for all general purposes, apart from calls
#-->min: 0, max: 31, step: 1, default: 28
echo 23 > /sys/class/misc/boeffla_sound/mic_level_general

#Speakers volume
#This value increases/decreases volume of internal speakers. First value is left, second value is right channel.
#-->min:0, max:63, steps:1
#echo "55 55" > /sys/class/misc/boeffla_sound/speaker_volume

#Speakers tuning
#This option enables the speaker tuning feature, which improves sound quality of internal speakers, by changing some equalizer settings (bass boost)
echo 1 > /sys/class/misc/boeffla_sound/speaker_tuning

#Headphones volume
#This value increases/decreases volume of headphones connected to the device. Does not affect bluetooth connections. First value is left, second value is right channel.
#-->min:0, max:63, steps:1
#echo "xx yy" > /sys/class/misc/boeffla_sound/headphone_volume

#Stereo expansion
#This value controls the depth of simulated 3D sound on 2-channel headphones.
#-->min: 0, max: 31, step: 1, default: 0
#echo xx > /sys/class/misc/boeffla_sound/stereo_expansion

#DAC direct
#By switching DAC direct to on, you will bypass the output mixer in the signal path and connect the DAC directly to the headphone amplifier
echo 1 > /sys/class/misc/boeffla_sound/dac_direct

#DAC oversampling
#This setting changes the oversampling rate from 64 to 128 bit
echo 1 > /sys/class/misc/boeffla_sound/dac_oversampling

#FLL tuning
#Tunes the audio chip clock engine, to ensure the right power to your headphones and reduce distorsions and bad behaviours
echo 1 > /sys/class/misc/boeffla_sound/fll_tuning

#Mono downmix
#This setting changes internal signal handling to switch to mono output for headphones
#echo 1 > /sys/class/misc/boeffla_sound/mono_downmix

#Kernel equalizer
#This switch controls the state of the hardware equalizer. SE stands for saturation prevention
#-->0:Disabled, 1:Enabled with SE, 2:Enabled without SE
#echo xx > /sys/class/misc/boeffla_sound/eq

#Kernel equalizer gains.
#-->min:-12, max:12, steps 1, default:0
#echo "0 0 0 0 0" > /sys/class/misc/boeffla_sound/eq_gains

#Privacy mode
#This setting causes the speakers to be completely muted for all sounds as long as headphones are plugged in. This is applied globally to the whole system
#echo 1 > /sys/class/misc/boeffla_sound/privacy_mode


#------Charge Levels (by Lord Boeffla)------#

#AC charge rate
#This configures the charging rate when you load your phone via an AC charger
#-->min:0 (off), max:2000, unit:mA, steps:100
#echo 1500 > /sys/kernel/charge_levels/charge_level_ac

#USB charge rate
#This configures the charging rate when you load your phone via an USB
#-->min:0 (off), max:2000, unit:mA, steps:100
#echo 500 > /sys/kernel/charge_levels/charge_level_usb

#Wireless charge rate
#This configures the charging rate when you load your phone via a wireless charging cover
#-->min:0 (off), max:2000, unit:mA, steps:100
#echo 500 > /sys/kernel/charge_levels/charge_level_wireless

#Ignore unstable power
#By switching this option to on, the charging logic will NOT reduce the charging current for faulty chargers with unstable power. Use at your own risk!
#echo 0 > /sys/kernel/charge_levels/ignore_unstable_power

#Ignore safety margin
#By switching this option to on, the further deduction of 100 mA after detecting a stable charging power will not be done. Use at your own risk!
#echo 0 > /sys/kernel/charge_levels/ignore_safety_margin


#--------------- LED notifications -----------------#

# Enable battery charge led notification
echo 1 > /sys/module/leds_an30259a/parameters/led_switch

#--------------- Kernel Tweaks ---------------------#
# Swappiness
echo 60 > /proc/sys/vm/swappiness


# zRAM
SIZE=300

# don't touch lines below
#-------------------------------------------------------
change_zram_size() {
	swapoff /dev/block/zram0
	echo 1 > /sys/devices/virtual/block/zram0/reset
	echo $(( $SIZE * 1024 * 1024 )) > /sys/devices/virtual/block/zram0/disksize
	mkswap /dev/block/zram0
	swapon /dev/block/zram0
}
sleep 10 && change_zram_size &
#--------------------------------------------------------

# LowMemoryKiller
ADJ="0,3,6,10,13,15"
MINFREE="10120,14280,18244,28000,32000,35000"

echo "com.android.systemui,com.android.phone" > /sys/module/lowmemorykiller/parameters/donotkill_proc_names
echo 1 > /sys/module/lowmemorykiller/parameters/donotkill_proc

#---------------------------------------------------------
chmod 0644 /sys/module/lowmemorykiller/parameters/minfree
chmod 0644 /sys/module/lowmemorykiller/parameters/adj
#echo $ADJ > /sys/module/lowmemorykiller/parameters/adj
#echo $MINFREE > /sys/module/lowmemorykiller/parameters/minfree
#chmod 0444 /sys/module/lowmemorykiller/parameters/adj
#chmod 0444 /sys/module/lowmemorykiller/parameters/minfree
#-----------------------------------------------------------
